name: calendar_widget
description: Simple and clean flutter calendar widget.
version: 0.2.2+10
homepage: https://github.com/bhavishassai/calendar_widget.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  dotted_border: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: 
