name: flutter_neat_and_clean_calendar
description: Simple and clean flutter calendar with ability to slide up/down to
  show weekly/monthly calendar. Fork of
  [flutter_clean_calender](https://pub.dev/packages/flutter_clean_calendar)
version: 0.2.2+10
homepage: https://github.com/rwbr/flutter_neat_and_clean_calendar

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  dotted_border: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: 
